- name: building image and checking health of url
  hosts: localhost

  tasks:
  - include: tasks/build-docker-image.yml
  - include: tasks/image-check.yml
  - include: tasks/check-status.yml
  - include: tasks/push-image.yml
