    - name: Log in to Docker Hub
      docker_login:
        username: "{{ hub_username }}"
        password: "{{ hub_password }}"
        reauthorize: yes
      register: login_results

    - debug:
        var: login_results
