    - name: pushing image to docker
      command: sudo docker push kiranp23/webapp:latest
      args:
         warn: no
      become_user: ubuntu

    - name:  stopping container
      command: sudo docker stop casestudy
      args:
         warn: no

    - name: removing container
      command: sudo docker rm casestudy
      args:
         warn: no

    - name: removing image from local
      command: sudo docker rmi kiranp23/webapp:latest
      args:
         warn: no
